postgresql:
  image: sameersbn/mysql:latest
  environment:
    - DB_USER=redmine
    - DB_PASS=password
    - DB_NAME=redmine_production
  volumes:
    - /srv/docker/redmine/mysql:/var/lib/mysql
redmine:
  image: sameersbn/redmine:3.1.1
  links:
    - mysql:mysql
  environment:
    - REDMINE_PORT=10083
    - SMTP_ENABLED=true
    - SMTP_DOMAIN=smtp.exmail.qq.com
    - SMTP_HOST=smtp.exmail.qq.com
    - SMTP_PORT=25
    - SMTP_USER=mailer@example.com
    - SMTP_PASS=password
    - SMTP_STARTTLS=false
    - SMTP_AUTHENTICATION=:login
  ports:
    - "10083:80"
  volumes:
    - /srv/docker/redmine/redmine:/home/redmine/data
